### ISSUE TITLE
Redux state mutations in reducers

### ISSUE THREAD

**Issue by ivan-aksamentov** [OHIF/ohif-core#21]
In our application, reducers of `ohif-core` cause failures of immutability checks as implemented by `redux-immutable-state-invariant` redux middleware.

So far we found 2 mutations: see PR #22 
There could be more. Please consider implementing a systematic review and automatic checking of the reducer code.

Some of the tools that help to avoid state-mutation-related bugs (or to find them early):
 - object spread (`@babel/plugin-proposal-object-rest-spread`) -  the golden standard of shallow-copying objects as of right now. It allows to avoid `Object.assign()`, which is arguably more verbose and error prone.
 - `redux-immutable-state-invariant` redux middleware
 - unit testing reducers and asserting immutability of input state

Additional info:
 - [Why immutability is required in Redux](https://redux.js.org/faq/immutable-data#why-is-immutability-required-by-redux)

**Comment by dannyrb** [comment]
👋 Hi @ivan-aksamentov, thanks for bringing this to our attention and for the PR. We're still feeling things out, so any suggestions in a similar vein are appreciated. Please don't hesitate to create PRs for anything else out of line with best practices.
