### ISSUE TITLE
Ideographic  Person Name support

### ISSUE THREAD

**Issue by char1st** [OHIF/ohif-core#37]
getName.js  not  handle Ideographic  Person Name

**Comment by dannyrb** [comment]
Is this a bug report or feature request? Do you have any suggestions around how this should be handled/implemented/fixed?

**Comment by char1st** [comment]
It is a bug report  also a  feature request .
Ideographic Person Name will  not  show in study list (old version viewer)   .
And in Viewers 2.0 ，will throw error.

copy from  Alphabetic PN
`if (element.Value[0].Alphabetic) {
    return element.Value[0].Alphabetic;
  }`
Just use  
`if (element.Value[0].Ideographic ) {
    return element.Value[0].Ideographic ;
  }`

**Comment by dannyrb** [comment]
@char1st do you feel comfortable making a PR for this functionality + test case?

**Comment by char1st** [comment]
if a PN  data   like that
```
{
	"00100010": {
		"vr": "PN",
		"Value": [{
			"Alphabetic": "A",
			"Ideographic": I",
			"Phonetic": P"
		}]
	}
}
```
with method  getName  which part  will return  in  Value ?  Or return all ['A','I','P'] as a array ?
