### ISSUE TITLE
I'm new and looking for documentation to understand this repo

### ISSUE THREAD

**Issue by yaoli** [OHIF/ohif-core#4]
I'm totally new to the world of OHIF, currently very confused about ohif-core, cornerstone, cornerstone-tools, and many other parts that build ohif-viewer. Can anyone provide any guidance to me. Eventually I'd very much like to get involved in development, making contribution to the codebase. Thank you in advance.

**Comment by swederik** [comment]
Hi there,

Sorry for the delay. We are in the midst of a big migration from the Meteor version of OHIF towards using React as a front-end framework. Right now there isn't really much documentation, and all of these new libraries (ohif-core, react-viewerbase, etc..) are still under development.

The best places to look are here:
https://docs.ohif.org/
https://docs.cornerstonejs.org/
https://tools.cornerstonejs.org/

For the current stable version of OHIF, all of the code is here: https://github.com/OHIF/Viewers/
The react version is here: https://github.com/OHIF/Viewers/tree/react

**Comment by paul-asvb** [comment]
Hello @swederik, that is a really good decision! Do you have any kind of architectural plan? how can i contribute? i have been working on my own cornerstone react implementation

**Comment by dannyrb** [comment]
I've updated the `README.md` to provide a bit more context on this repository and how to contribute: https://github.com/OHIF/ohif-core/blob/master/README.md

If there are API changes or features you would like to propose, feel free to create a new issue and we can discuss 😄. https://docs.ohif.org/ will be receiving an update soon that better illustrates how these all tie together:

- [ohif-core](https://github.com/OHIF/ohif-core)
- [react-viewerbase](https://github.com/OHIF/react-viewerbase)
- [Viewers](https://github.com/OHIF/Viewers)

If there's anything in specific you would like to see better explained, please don't hesitate to request documentation.
