### ISSUE TITLE
qidoSupportsIncludeField should be true by default

### ISSUE THREAD

**Issue by swederik** [OHIF/ohif-core#63]
Currently if `qidoSupportsIncludeField` is not specified, the value will be left as undefined which is falsy. It would be better for this to be true by default, since it is generally well supported.

https://github.com/OHIF/ohif-core/blob/38547f4f491ba51245f94e281247e44067f57cf6/src/studies/services/qido/studies.js#L122

**Comment by dannyrb** [comment]
This will need to be re-added to `OHIF/Viewers`. I'll create an issue.
